name: TestBuild

on: 
  push:
    branches:
      - develop
      - feature/*
      - bugfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: SetUp Enviroment
        working-directory: ./
        run: ./CI/setupEnv.sh

      - name: Run build OPGLTools
        working-directory: ./
        run: ./CI/testbuild_opGLTools.sh

      - name: Run build Gravity Projects
        working-directory: ./
        run: ./CI/testbuild_Gravity.sh
      
      - name: Run build Game Projects
        working-directory: ./
        run: ./CI/testbuild_Games.sh